@echo off
setlocal

if "%NODECHAT_SSH_USER%"=="" set "NODECHAT_SSH_USER=bmoore_77"
if "%NODECHAT_SSH_HOST%"=="" set "NODECHAT_SSH_HOST=192.168.1.198"
if "%NODECHAT_HISTORY_BIND%"=="" set "NODECHAT_HISTORY_BIND=172.17.0.1"
if "%NODECHAT_HISTORY_PORT%"=="" set "NODECHAT_HISTORY_PORT=8765"

echo Opening AI History SSH tunnel.
echo Leave this window open while using nodechat history.
echo.
echo local:  127.0.0.1:%NODECHAT_HISTORY_PORT%
echo remote: %NODECHAT_HISTORY_BIND%:%NODECHAT_HISTORY_PORT% on %NODECHAT_SSH_USER%@%NODECHAT_SSH_HOST%
echo.

ssh -L %NODECHAT_HISTORY_PORT%:%NODECHAT_HISTORY_BIND%:%NODECHAT_HISTORY_PORT% %NODECHAT_SSH_USER%@%NODECHAT_SSH_HOST%

